In [5]:
import pandas as pd

In [19]:
json_df = pd.read_json(r"C:\Users\Heisgolden\Downloads\json_sample.json")

In [20]:
csv_df = pd.read_csv(r"C:\Users\Heisgolden\Downloads\countries of the world.csv")

In [21]:
txt_df = pd.read_csv(r"C:\Users\Heisgolden\Downloads\countries of the world.txt", sep="\t")

In [9]:
df = pd.read_excel(r"C:\Users\Heisgolden\Downloads\world_population_excel_workbook.xlsx")

In [10]:
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El AaiÃºn,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

In [14]:
df[df['Rank'] <= 10]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
16,8,BGD,Bangladesh,Dhaka,Asia,171186372,167420951,157830000,148391139,129193327,107147651,83929765,67541860,147570,1160.0350,1.0108,2.15
27,7,BRA,Brazil,Brasilia,South America,215313498,213196304,205188205,196353492,175873720,150706446,122288383,96369875,8515767,25.2841,1.0046,2.70
41,1,CHN,China,Beijing,Asia,1425887337,1424929781,1393715448,1348191368,1264099069,1153704252,982372466,822534450,9706961,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1417173173,1396387127,1322866505,1240613620,1059633675,870452165,696828385,557501301,3287590,431.0675,1.0068,17.77
93,4,IDN,Indonesia,Jakarta,Asia,275501339,271857970,259091970,244016173,214072421,182159874,148177096,115228394,1904569,144.6529,1.0064,3.45
131,10,MEX,Mexico,Mexico City,North America,127504125,125998302,120149897,112532401,97873442,81720428,67705186,50289306,1964375,64.9082,1.0063,1.60
149,6,NGA,Nigeria,Abuja,Africa,218541212,208327405,183995785,160952853,122851984,95214257,72951439,55569264,923768,236.5759,1.0241,2.74
156,5,PAK,Pakistan,Islamabad,Asia,235824862,227196741,210969298,194454498,154369924,115414069,80624057,59290872,881912,267.4018,1.0191,2.96
171,9,RUS,Russia,Moscow,Europe,144713314,145617329,144668389,143242599,146844839,148005704,138257420,130093010,17098242,8.4636,0.9973,1.81
221,3,USA,United States,"Washington, D.C.",North America,338289857,335942003,324607776,311182845,282398554,248083732,223140018,200328340,9372610,36.0935,1.0038,4.24

In [13]:
print(df.columns.tolist())

['Rank', 'CCA3', 'Country', 'Capital', 'Continent', '2022 Population', '2020 Population', '2015 Population', '2010 Population', '2000 Population', '1990 Population', '1980 Population', '1970 Population', 'Area (kmÂ²)', 'Density (per kmÂ²)', 'Growth Rate', 'World Population Percentage']

In [17]:
specific_countries =['Bangladesh','Brazil']
df[df['Country'].isin(specific_countries)]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
16,8,BGD,Bangladesh,Dhaka,Asia,171186372,167420951,157830000,148391139,129193327,107147651,83929765,67541860,147570,1160.0350,1.0108,2.15
27,7,BRA,Brazil,Brasilia,South America,215313498,213196304,205188205,196353492,175873720,150706446,122288383,96369875,8515767,25.2841,1.0046,2.70

In [18]:
df[df['Country'].str.contains('United')]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
219,97,ARE,United Arab Emirates,Abu Dhabi,Asia,9441129,9287289,8916899,8481771,3275333,1900151,1014048,298084,83600,112.9322,1.0081,0.12
220,21,GBR,United Kingdom,London,Europe,67508936,67059474,65224364,62760039,58850043,57210442,56326328,55650166,242900,277.9289,1.0034,0.85
221,3,USA,United States,"Washington, D.C.",North America,338289857,335942003,324607776,311182845,282398554,248083732,223140018,200328340,9372610,36.0935,1.0038,4.24
222,200,VIR,United States Virgin Islands,Charlotte Amalie,North America,99465,100442,102803,106142,108185,100685,96640,63446,347,286.6427,0.9937,0.00

In [22]:
df2 = df.set_index('Country')
df2

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
Western Sahara,172,ESH,El AaiÃºn,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

In [26]:
df2.filter(items = ['Continent','CCA3'], axis = 1)

                  Continent CCA3
Country
Afghanistan            Asia  AFG
Albania              Europe  ALB
Algeria              Africa  DZA
American Samoa      Oceania  ASM
Andorra              Europe  AND
...                     ...  ...
Wallis and Futuna   Oceania  WLF
Western Sahara       Africa  ESH
Yemen                  Asia  YEM
Zambia               Africa  ZMB
Zimbabwe             Africa  ZWE

[234 rows x 2 columns]

In [29]:
df2.filter(like = 'United', axis = 0)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
United Arab Emirates,97,ARE,Abu Dhabi,Asia,9441129,9287289,8916899,8481771,3275333,1900151,1014048,298084,83600,112.9322,1.0081,0.12
United Kingdom,21,GBR,London,Europe,67508936,67059474,65224364,62760039,58850043,57210442,56326328,55650166,242900,277.9289,1.0034,0.85
United States,3,USA,"Washington, D.C.",North America,338289857,335942003,324607776,311182845,282398554,248083732,223140018,200328340,9372610,36.0935,1.0038,4.24
United States Virgin Islands,200,VIR,Charlotte Amalie,North America,99465,100442,102803,106142,108185,100685,96640,63446,347,286.6427,0.9937,0.00

In [30]:
df2.loc['United States']

Rank                                          3
CCA3                                        USA
Capital                        Washington, D.C.
Continent                         North America
2022 Population                       338289857
2020 Population                       335942003
2015 Population                       324607776
2010 Population                       311182845
2000 Population                       282398554
1990 Population                       248083732
1980 Population                       223140018
1970 Population                       200328340
Area (kmÂ²)                             9372610
Density (per kmÂ²)                      36.0935
Growth Rate                              1.0038
World Population Percentage                4.24
Name: United States, dtype: object

# Grouping by aggregation

In [3]:
import pandas as pd

In [6]:
df = pd.read_excel(r"C:\Users\Heisgolden\Downloads\world_population_excel_workbook.xlsx")

In [8]:
df.groupby('Continent')

In [9]:
group_by_frame = df.groupby('Continent')

In [11]:
group_by_frame.mean(numeric_only=True)

,Rank,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
Continent,,,,,,,,,,,,,
Africa,92.157895,2.503037e+07,2.387144e+07,2.107197e+07,1.851277e+07,1.436747e+07,1.119563e+07,8.448007e+06,6.411304e+06,5.318941e+05,125.047646,1.021244,0.313509
Asia,77.560000,9.442767e+07,9.326173e+07,8.916500e+07,8.440083e+07,7.470179e+07,6.421127e+07,5.270668e+07,4.289813e+07,6.427628e+05,1025.024136,1.009384,1.183800
Europe,124.500000,1.486295e+07,1.491584e+07,1.483071e+07,1.471228e+07,1.452187e+07,1.440642e+07,1.385054e+07,1.311848e+07,4.602082e+05,663.324742,1.002256,0.186600
North America,160.925000,1.500740e+07,1.485591e+07,1.425960e+07,1.356802e+07,1.215174e+07,1.053166e+07,9.207334e+06,7.885865e+06,6.061044e+05,272.761758,1.004175,0.187750
Oceania,188.521739,1.958198e+06,1.910149e+06,1.756664e+06,1.613164e+06,1.357512e+06,1.162775e+06,9.965322e+05,8.469683e+05,3.702209e+05,132.543065,1.007383,0.023913
South America,97.571429,3.120119e+07,3.082357e+07,2.950960e+07,2.807702e+07,2.497388e+07,2.122474e+07,1.727064e+07,1.378194e+07,1.273813e+06,20.971979,1.007957,0.391429

In [12]:
df.groupby('Continent').count()

,Rank,CCA3,Country,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
Continent,,,,,,,,,,,,,,,,
Africa,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57
Asia,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50
Europe,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50
North America,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40
Oceania,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23
South America,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14

In [13]:
group_by_frame.min()

,Rank,CCA3,Country,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
Continent,,,,,,,,,,,,,,,,
Africa,6,AGO,Algeria,Abuja,107118,105530,99240,92409,80060,71057,52233,35383,374,2.1654,1.0004,0.00
Asia,1,AFG,Afghanistan,Abu Dhabi,449002,441725,421437,361575,282507,224957,164887,118007,30,2.1727,0.9816,0.01
Europe,9,ALB,Albania,Amsterdam,510,520,564,596,651,700,733,752,1,3.6204,0.9120,0.00
North America,3,ABW,Anguilla,Basse-Terre,4390,4500,5059,4938,5138,5168,2983,2417,21,0.0261,0.9937,0.00
Oceania,55,ASM,American Samoa,Alofi,1871,1827,1454,1367,1666,1669,1647,1714,12,3.4032,0.9831,0.00
South America,7,ARG,Argentina,AsunciÃ³n,3780,3747,3408,3187,3080,2332,2240,2274,12173,0.3105,0.9990,0.00

In [14]:
group_by_frame.max()

,Rank,CCA3,Country,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
Continent,,,,,,,,,,,,,,,,
Africa,196,ZWE,Zimbabwe,Yaounde,218541212,208327405,183995785,160952853,122851984,95214257,72951439,55569264,2381741,871.9278,1.0378,2.74
Asia,175,YEM,Yemen,Yerevan,1425887337,1424929781,1393715448,1348191368,1264099069,1153704252,982372466,822534450,9706961,23172.2667,1.0376,17.88
Europe,234,VAT,Vatican City,Zagreb,144713314,145617329,144668389,143242599,146844839,148005704,138257420,130093010,17098242,18234.5000,1.0691,1.81
North America,230,VIR,United States Virgin Islands,Willemstad,338289857,335942003,324607776,311182845,282398554,248083732,223140018,200328340,9984670,1299.2647,1.0150,4.24
Oceania,233,WSM,Wallis and Futuna,Yaren,26177413,25670051,23820236,22019168,19017963,17048003,14706322,12595034,7692024,603.2381,1.0238,0.33
South America,231,VEN,Venezuela,Sucre,215313498,213196304,205188205,196353492,175873720,150706446,122288383,96369875,8515767,65.0229,1.0239,2.70

In [15]:
group_by_frame.sum(numeric_only=True)

,Rank,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
Continent,,,,,,,,,,,,,
Africa,5253,1426730932,1360671810,1201102442,1055228072,818946032,638150629,481536377,365444348,30317963,7127.7158,58.2109,17.87
Asia,3878,4721383274,4663086535,4458250182,4220041327,3735089604,3210563577,2635334228,2144906290,32138141,51251.2068,50.4692,59.19
Europe,6225,743147538,745792196,741535608,735613934,726093423,720320797,692527159,655923991,23010411,33166.2371,50.1128,9.33
North America,6437,600296136,594236593,570383850,542720651,486069584,421266425,368293361,315434606,24244178,10910.4703,40.1670,7.51
Oceania,4336,45038554,43933426,40403283,37102764,31222778,26743822,22920240,19480270,8515081,3048.4905,23.1698,0.55
South America,1366,436816608,431530043,413134396,393078250,349634282,297146415,241789006,192947156,17833382,293.6077,14.1114,5.48

In [16]:
df.groupby('Continent').agg({
    'Growth Rate': ['mean', 'max', 'min']})

              Growth Rate
                     mean     max     min
Continent
Africa           1.021244  1.0378  1.0004
Asia             1.009384  1.0376  0.9816
Europe           1.002256  1.0691  0.9120
North America    1.004175  1.0150  0.9937
Oceania          1.007383  1.0238  0.9831
South America    1.007957  1.0239  0.9990

In [17]:
df.groupby('Continent').agg({
    '2022 Population': ['mean', 'max', 'sum'],
    'Density (per kmÂ²)': ['mean', 'max'],
    'Growth Rate': ['mean', 'min', 'max']
})

              2022 Population                         Density (per kmÂ²)  \
                         mean         max         sum               mean
Continent
Africa           2.503037e+07   218541212  1426730932         125.047646
Asia             9.442767e+07  1425887337  4721383274        1025.024136
Europe           1.486295e+07   144713314   743147538         663.324742
North America    1.500740e+07   338289857   600296136         272.761758
Oceania          1.958198e+06    26177413    45038554         132.543065
South America    3.120119e+07   215313498   436816608          20.971979

                          Growth Rate
                      max        mean     min     max
Continent
Africa           871.9278    1.021244  1.0004  1.0378
Asia           23172.2667    1.009384  0.9816  1.0376
Europe         18234.5000    1.002256  0.9120  1.0691
North America   1299.2647    1.004175  0.9937  1.0150
Oceania          603.2381    1.007383  0.9831  1.0238
South America     65.0229    1.007957  0.9990  1.0239

In [18]:
group_by_frame.describe()

               Rank                                                      \
              count        mean        std   min     25%    50%     75%
Continent
Africa         57.0   92.157895  53.826703   6.0   50.00   77.0  145.00
Asia           50.0   77.560000  53.633739   1.0   30.50   69.5  121.25
Europe         50.0  124.500000  61.993828   9.0   88.50  122.5  168.75
North America  40.0  160.925000  62.976751   3.0  121.00  187.5  206.50
Oceania        23.0  188.521739  45.142068  55.0  182.00  194.0  222.50
South America  14.0   97.571429  68.429317   7.0   45.75   73.5  156.25

                     2022 Population                ... Growth Rate          \
                 max           count          mean  ...         75%     max
Continent                                           ...
Africa         196.0            57.0  2.503037e+07  ...    1.026300  1.0378
Asia           175.0            50.0  9.442767e+07  ...    1.015000  1.0376
Europe         234.0            50.0  1.486295e+07  ...    1.006650  1.0691
North America  230.0            40.0  1.500740e+07  ...    1.007950  1.0150
Oceania        233.0            23.0  1.958198e+06  ...    1.012200  1.0238
South America  231.0            14.0  3.120119e+07  ...    1.011025  1.0239

              World Population Percentage                                    \
                                    count      mean       std   min     25%
Continent
Africa                               57.0  0.313509  0.471129  0.00  0.0300
Asia                                 50.0  1.183800  3.507563  0.01  0.0700
Europe                               50.0  0.186600  0.341925  0.00  0.0100
North America                        40.0  0.187750  0.707297  0.00  0.0000
Oceania                              23.0  0.023913  0.073159  0.00  0.0000
South America                        14.0  0.391429  0.698767  0.00  0.0175


                 50%     75%    max
Continent
Africa         0.170  0.3700   2.74
Asia           0.225  0.6275  17.88
Europe         0.065  0.1300   1.81
North America  0.000  0.0650   4.24
Oceania        0.000  0.0000   0.33
South America  0.190  0.4100   2.70

[6 rows x 104 columns]

In [22]:
# cleaning Dataset

In [23]:
df.isnull().sum()

Rank                           0
CCA3                           0
Country                        0
Capital                        0
Continent                      0
2022 Population                0
2020 Population                0
2015 Population                0
2010 Population                0
2000 Population                0
1990 Population                0
1980 Population                0
1970 Population                0
Area (kmÂ²)                    0
Density (per kmÂ²)             0
Growth Rate                    0
World Population Percentage    0
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df = df.drop_duplicates()